[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "tpov"
authors = [{name = "Cyril Li", email = "cyrils.li@icloud.com"}]
dynamic = ["version", "description"]
